services:
  app:
    build: .                                                                                                                                            ports:
      - "4001:4001"
    env_file:
      - .env
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && node dist/app.js"
    networks:
      - servicios_default

networks:
  servicios_default:
    external: true

volumes: {}